In [6]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('us-cities-table.csv')

In [4]:
df

,pop2024,city,state,usps,pop2020,densityMi,growth,areaMi,type,slug,rank
0,8097282,New York City,New York,NY,8740292,26950,-0.01947,300.457,City,new-york/new-york,1
1,3795936,Los Angeles,California,CA,3895848,8068,-0.00654,470.517,City,california/los-angeles,2
2,2638159,Chicago,Illinois,IL,2743329,11584,-0.00987,227.748,City,illinois/chicago,3
3,2319119,Houston,Texas,TX,2299269,3620,0.00214,640.606,City,texas/houston,4
4,1662607,Phoenix,Arizona,AZ,1612459,3208,0.00760,518.331,City,arizona/phoenix,5
...,...,...,...,...,...,...,...,...,...,...,...
345,100816,Chico,California,CA,102755,2920,-0.00479,34.521,City,california/chico,346
346,100736,Fort Myers,Florida,FL,87279,2518,0.03455,39.999,City,florida/fort-myers,347
347,100595,New Bedford,Massachusetts,MA,100993,5029,-0.00099,20.001,City,massachusetts/new-bedford,348
348,100550,Boca Raton,Florida,FL,98246,3446,0.00576,29.178,City,florida/boca-raton,349
349,100304,Deltona,Florida,FL,94044,2687,0.01585,37.324,City,florida/deltona,350

In [9]:
df['log_pop'] = np.log(df['pop2024'])
df['log_density'] = np.log(df['densityMi'])

In [12]:
durham_row = df[df['city'] == 'Durham']

In [17]:
durham_pop = durham_row['log_pop'].iloc[0]
durham_density = durham_row['log_density'].iloc[0]

In [18]:
durham_density

7.851661177889265

In [31]:
df['log_pop_diff'] = np.abs(df['log_pop'] - durham_pop)
df['log_density_diff'] = np.abs(df['log_density'] - durham_density)

In [32]:
df['log_agg_diff'] = df['log_pop_diff'] + df['log_density_diff']

In [34]:
df = df.sort_values(by='log_agg_diff', axis=0)

In [39]:
for i, row in df.iterrows():
    print(row['city'])

Durham
Reno
North Las Vegas
Greensboro
Fort Wayne
Lincoln
Orlando
Laredo
Henderson
Boise City
Port St. Lucie
Corpus Christi
Wichita
Aurora
Madison
Baton Rouge
Sioux Falls
Toledo
New Orleans
Cape Coral
Bakersfield
Fremont
Lubbock
Overland Park
Des Moines
Santa Clarita
Winston-Salem
Grand Prairie
Cincinnati
Plano
Riverside
Newport News
Tulsa
Spokane
Gilbert
Frisco
Colorado Springs
Glendale
Irving
McKinney
Enterprise
Chandler
Murfreesboro
San Bernardino
Akron
St. Petersburg
St. Louis
Salt Lake City
Knoxville
Tampa
Tallahassee
Amarillo
Cary
Richmond
Irvine
Fort Collins
Garland
Raleigh
Tucson
Omaha
Stockton
Virginia Beach
Killeen
Pittsburgh
Cleveland
Olathe
Albuquerque
Arlington
Norfolk
McAllen
Springfield
Little Rock
Clarksville
Joliet
Louisville
St. Paul
Hampton
Moreno Valley
Gainesville
Fargo
El Paso
Ontario
Tacoma
Chula Vista
Scottsdale
Dayton
Mesquite
Rockford
Salem
Vancouver
Pearland
Mesa
Lexington
College Station
Honolulu
Rancho Cucamonga
Memphis
Atlanta
Wilmington
Hayward
Billings
Aurora
New Braunfels
Fayetteville
West Palm Beach
Grand Rapids
Menifee
Eugene
Roseville
Pasadena
Lakewood
Modesto
Kansas City
Fontana
The Woodlands
Lancaster
Shreveport
Elk Grove
Santa Rosa
Paradise
Denton
Evansville
Brownsville
Provo
Fairfield
Simi Valley
Oceanside
Jurupa Valley
Thousand Oaks
Lewisville
Sugar Land
Victorville
Buffalo
Rochester
League City
Tempe
Corona
Lafayette
Greeley
Anaheim
Birmingham
Odessa
Midland
Lansing
Naperville
Edinburg
Arvada
South Bend
Topeka
Fort Myers
Columbia
Visalia
Elgin
Riverview
Chattanooga
Round Rock
Peoria
Carlsbad
Indianapolis
Spokane Valley
Sandy Springs
Stamford
Cedar Rapids
Worcester
Escondido
Deltona
Temecula
Green Bay
Meridian
Carrollton
High Point
Thornton
Sparks
Sterling Heights
Surprise
Spring Hill
Fishers
Palmdale
West Valley City
Rochester
Mobile
Waco
Lakeland
Montgomery
Spring Valley
Huntsville
Broken Arrow
Fresno
Davie
Bend
Nampa
Peoria
Fort Lauderdale
Palm Bay
Chico
Warren
Kent
Sunrise Manor
Everett
Murrieta
Bellevue
Brandon
Manchester
Pueblo
Charlotte
Carmel
Pembroke Pines
Tyler
West Jordan
Charleston
Sacramento
Columbia
Springfield
Fort Worth
Westminster
Tuscaloosa
Detroit
Portland
Springfield
Concord
Glendale
Vallejo
Savannah
Austin
Centennial
Richmond
Fayetteville
Vacaville
North Charleston
Concord
Boca Raton
Antioch
Chesapeake
Georgetown
Miramar
Las Vegas
Nashville
Richardson
Waterbury
Ann Arbor
Independence
Columbus
Milwaukee
Kansas City
Lehigh Acres
Hollywood
Minneapolis
Huntington Beach
Boulder
Denver
Jackson
Oakland
Oxnard
Las Cruces
Allen
Clearwater
Lee's Summit
Arlington
Conroe
Clovis
Hillsboro
Orange
Santa Ana
Syracuse
Highlands Ranch
Dearborn
Rialto
Abilene
Pompano Beach
Columbus
Newark
Renton
Gresham
Salinas
Baltimore
Metairie
Long Beach
Pomona
Pasadena
Coral Springs
Columbia
Beaumont
Santa Maria
St. George
Oklahoma City
Fullerton
Wichita Falls
Sunnyvale
San Buenaventura (Ventura)
San Tan Valley
Athens
Hialeah
Albany
Brockton
Hesperia
Torrance
South Fulton
Augusta
New Bedford
San Antonio
New Haven
Rio Rancho
Miami Gardens
Providence
Santa Clara
Jacksonville
Dallas
Yonkers
Garden Grove
Palm Coast
Allentown
San Jose
Hartford
Burbank
Phoenix
Quincy
Bridgeport
West Covina
Costa Mesa
Miami
San Diego
Alexandria
Macon-Bibb County
Jersey City
El Cajon
Norman
Lowell
Seattle
Yuma
Downey
Elizabeth
Washington
Lynn
Goodyear
Houston
Berkeley
Boston
El Monte
Inglewood
Paterson
East Los Angeles
Anchorage
San Francisco
Cambridge
Philadelphia
Buckeye
Suffolk
Chicago
Los Angeles
New York City

In [36]:
df.head(100)

,pop2024,city,state,usps,pop2020,densityMi,growth,areaMi,type,slug,rank,log_pop,log_density,log_pop_diff,log_density_diff,log_agg_diff
69,300100,Durham,North Carolina,NC,284444,2570,0.01321,116.754,City,north-carolina/durham,70,12.611871,7.851661,0.000000,0.000000,0.000000
77,278226,Reno,Nevada,NV,264981,2553,0.01204,108.993,City,nevada/reno,78,12.536189,7.845024,0.075682,0.006637,0.082319
71,292623,North Las Vegas,Nevada,NV,261214,2778,0.02757,105.319,City,nevada/north-las-vegas,72,12.586640,7.929487,0.025231,0.077825,0.103056
65,304279,Greensboro,North Carolina,NC,296345,2273,0.00656,133.861,City,north-carolina/greensboro,66,12.625700,7.728856,0.013829,0.122805,0.136635
82,271865,Fort Wayne,Indiana,IN,264380,2457,0.00693,110.628,City,indiana/fort-wayne,83,12.513061,7.806696,0.098810,0.044965,0.143775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,174312,Rancho Cucamonga,California,CA,174683,3748,-0.00053,46.510,City,california/rancho-cucamonga,157,12.068602,8.228978,0.543269,0.377316,0.920585
28,613110,Memphis,Tennessee,TN,635225,2070,-0.00894,296.202,City,tennessee/memphis,29,13.326300,7.635304,0.714429,0.216357,0.930786
35,514465,Atlanta,Georgia,GA,499896,3804,0.00713,135.253,City,georgia/atlanta,36,13.150883,8.243808,0.539012,0.392147,0.931159
237,125007,Wilmington,North Carolina,NC,115770,2431,0.01882,51.414,City,north-carolina/wilmington,238,11.736125,7.796058,0.875746,0.055603,0.931349
177,153344,Hayward,California,CA,162666,3347,-0.01497,45.818,City,california/hayward,178,11.940439,8.115820,0.671432,0.264159,0.935591

In [44]:
keys = {'Durham', 'Greensboro', 'Fort Wayne', 'Henderson', 'Wichita', 'Aurora', 'Madison', 'New Orleans', 'Bakersfield', 'Lubbock', 'Winston-Salem', 'Cincinnati'
       'Plano', 'Tulsa', 'Gilbert', 'San Bernadino', 'St. Petersburg'}

In [47]:
df_trimmed = df[df['city'].isin(keys)].reset_index(drop=True)

In [48]:
df_trimmed

,pop2024,city,state,usps,pop2020,densityMi,growth,areaMi,type,slug,rank,log_pop,log_density,log_pop_diff,log_density_diff,log_agg_diff
0,300100,Durham,North Carolina,NC,284444,2570,0.01321,116.754,City,north-carolina/durham,70,12.611871,7.851661,0.000000,0.000000,0.000000
1,304279,Greensboro,North Carolina,NC,296345,2273,0.00656,133.861,City,north-carolina/greensboro,66,12.625700,7.728856,0.013829,0.122805,0.136635
2,271865,Fort Wayne,Indiana,IN,264380,2457,0.00693,110.628,City,indiana/fort-wayne,83,12.513061,7.806696,0.098810,0.044965,0.143775
3,343382,Henderson,Nevada,NV,319072,2849,0.01802,120.523,City,nevada/henderson,55,12.746599,7.954723,0.134728,0.103062,0.237790
4,395484,Wichita,Kansas,KS,398024,2427,-0.00160,162.941,City,kansas/wichita,52,12.887866,7.794411,0.275995,0.057250,0.333245
5,397811,Aurora,Colorado,CO,386773,2440,0.00698,163.009,City,colorado/aurora,51,12.893732,7.799753,0.281861,0.051908,0.333769
6,282005,Madison,Wisconsin,WI,275204,3394,0.00606,83.088,City,wisconsin/madison,76,12.549680,8.129764,0.062191,0.278103,0.340294
7,357767,New Orleans,Louisiana,LA,383241,2111,-0.01749,169.500,City,louisiana/new-orleans,54,12.787637,7.654917,0.175766,0.196744,0.372510
8,416081,Bakersfield,California,CA,405280,2769,0.00653,150.273,City,california/bakersfield,47,12.938635,7.926242,0.326764,0.074580,0.401345
9,269833,Lubbock,Texas,TX,258013,1901,0.01107,141.961,City,texas/lubbock,84,12.505559,7.550135,0.106313,0.301526,0.407838
10,254032,Winston-Salem,North Carolina,NC,249804,1902,0.00418,133.584,City,north-carolina/winston-salem,91,12.445216,7.550661,0.166656,0.301000,0.467655
11,411308,Tulsa,Oklahoma,OK,413651,2080,-0.00142,197.765,City,oklahoma/tulsa,48,12.927098,7.640123,0.315227,0.211538,0.526765
12,277490,Gilbert,Arizona,AZ,269173,4041,0.00755,68.663,Town,arizona/gilbert,79,12.533540,8.304247,0.078331,0.452586,0.530917
13,264982,St. Petersburg,Florida,FL,259266,4287,0.00542,61.804,City,florida/st-petersburg,85,12.487417,8.363342,0.124454,0.511681,0.636135
14,176679,Aurora,Illinois,IL,180215,3922,-0.00498,45.051,City,illinois/aurora,154,12.082090,8.274357,0.529781,0.422696,0.952477