In [1]:
import pandas as pd

import os

In [4]:
def list_all_files(directory):
    # Loop over all directories and files in the given directory
    paths = []
    for dirpath, dirnames, filenames in os.walk(directory):
        for filename in filenames:
            # Full path of the file
            full_path = os.path.join(dirpath, filename)
            if '.csv' in filename[-4:]:
                paths.append(full_path)
    return paths

# Example usage:
directory_path = 'open_policing_comparison/'  # Replace with your directory path
files = list_all_files(directory_path)

In [5]:
files

['open_policing_comparison/nc_greensboro_2020_04_01.csv',
 'open_policing_comparison/tx_lubbock_2020_04_01.csv',
 'open_policing_comparison/nv_henderson_2020_04_01.csv',
 'open_policing_comparison/la_new_orleans_2020_04_01.csv',
 'open_policing_comparison/nc_durham_2020_04_01.csv',
 'open_policing_comparison/ok_tulsa_2020_04_01.csv',
 'open_policing_comparison/co_aurora_2023_01_26.csv',
 'open_policing_comparison/tx_plano_2020_04_01.csv',
 'open_policing_comparison/ks_wichita_2023_01_26.csv',
 'open_policing_comparison/yg821jf8611_az_gilbert_2020_04_01.csv',
 'open_policing_comparison/yg821jf8611_fl_saint_petersburg_2020_04_01.csv',
 'open_policing_comparison/ca_bakersfield_2020_04_01.csv',
 'open_policing_comparison/wi_madison_2023_01_26.csv',
 'open_policing_comparison/oh_cincinnati_2020_04_01.csv',
 'open_policing_comparison/nc_winston-salem_2020_04_01.csv',
 'open_policing_comparison/yg821jf8611_in_fort_wayne_2020_04_01.csv',
 'open_policing_comparison/yg821jf8611_ca_san_bernardino_2020_04_01.csv']

In [7]:
dfs = []
for f in files:
    df_init = pd.read_csv(f)
    #df_init.to_feather(f[:-4] + '.feather')
    df_init['file'] = f
    #df = dd.concat([df, df_init], axis=1, ignore_index=True)
    dfs.append(df_init)
    print(f)

open_policing_comparison/nc_greensboro_2020_04_01.csv
open_policing_comparison/tx_lubbock_2020_04_01.csv
open_policing_comparison/nv_henderson_2020_04_01.csv

/tmp/ipykernel_2138936/2876266148.py:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_init = pd.read_csv(f)

open_policing_comparison/la_new_orleans_2020_04_01.csv
open_policing_comparison/nc_durham_2020_04_01.csv
open_policing_comparison/ok_tulsa_2020_04_01.csv

/tmp/ipykernel_2138936/2876266148.py:3: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_init = pd.read_csv(f)

open_policing_comparison/co_aurora_2023_01_26.csv

/tmp/ipykernel_2138936/2876266148.py:3: DtypeWarning: Columns (3,6,7,11,12,22,26,27,28,29,30,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df_init = pd.read_csv(f)

open_policing_comparison/tx_plano_2020_04_01.csv

/tmp/ipykernel_2138936/2876266148.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_init = pd.read_csv(f)

open_policing_comparison/ks_wichita_2023_01_26.csv
open_policing_comparison/yg821jf8611_az_gilbert_2020_04_01.csv
open_policing_comparison/yg821jf8611_fl_saint_petersburg_2020_04_01.csv
open_policing_comparison/ca_bakersfield_2020_04_01.csv

/tmp/ipykernel_2138936/2876266148.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_init = pd.read_csv(f)

open_policing_comparison/wi_madison_2023_01_26.csv
open_policing_comparison/oh_cincinnati_2020_04_01.csv

/tmp/ipykernel_2138936/2876266148.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_init = pd.read_csv(f)

open_policing_comparison/nc_winston-salem_2020_04_01.csv
open_policing_comparison/yg821jf8611_in_fort_wayne_2020_04_01.csv
open_policing_comparison/yg821jf8611_ca_san_bernardino_2020_04_01.csv

In [8]:
df = pd.concat(dfs, axis=0)

In [9]:
df

,raw_row_number,date,time,location,county_name,subject_age,subject_race,subject_sex,officer_id_hash,department_name,...,raw_contraband_found,raw_results,raw_defendant_race,raw_defendant_ethnicity,raw_statute_name,raw_statute_section,neighborhood,raw_action_taken_cid,raw_field_subject_cid,raw_CallType
0,74627,2000-01-06,23:25:00,Unknown,NaN,23.0,white,female,22e35044ed,UNC Greensboro University Police Department,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,74634,2000-01-06,23:55:00,Unknown,NaN,19.0,white,female,22e35044ed,UNC Greensboro University Police Department,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,74638,2000-01-06,21:36:00,Unknown,NaN,22.0,black,male,22e35044ed,UNC Greensboro University Police Department,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,74650,2000-01-07,02:30:00,Unknown,NaN,14.0,black,male,22e35044ed,UNC Greensboro University Police Department,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,74654,2000-01-07,04:15:00,Unknown,NaN,19.0,black,male,22e35044ed,UNC Greensboro University Police Department,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90518,6,2017-09-18,85833,PERRIS HILL PARK,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CKS
90519,5,2017-09-19,144,W 5TH ST & N ARROWHEAD AVE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T
90520,3|4,2017-09-19,2657,157 W 5TH ST,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CKS
90521,2,2017-09-19,22010,EB 210 / SWY,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T
90522,1,2017-09-19,24298,W 6TH ST & N H ST,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T

In [12]:
df['datetime'] = pd.to_datetime(df['date'])
df = df.reset_index(drop=True)

In [16]:
import re
def slice_string(s):
    if isinstance(s, str):
        # Find the last '/' character
        last_slash_index = s.rfind('/')

        # Find the first numerical character after the last '/'
        match = re.search(r'\d', s[last_slash_index + 1:])

        if match:
            # Get the position of the first numerical character after the last '/'
            first_digit_index = last_slash_index + 1 + match.start()

            # Slice the string between the last '/' and the first numerical character
            return s[last_slash_index + 1:first_digit_index-1]
        else:
            return 'error'  # In case no numerical character is found
    else:
        return 'error'

In [17]:
df['file_source'] = df['file'].apply(slice_string).astype('category')

In [19]:
def process_string(s):
    # Check if the string contains a comma
    if not isinstance(s, str):
        return 'error'
    if s != None and ',' in s:
        # Find the part after the last comma
        result = s.split(',')[-1].strip().lower()
        return result
    else:
        # Return the string as is if no comma is found
        return s

df['location_categorical'] = df['location'].apply(process_string).astype('category')

In [20]:
df['location_categorical'].unique()

['Unknown', 'guilford county', 'yancey county', 'greene county', 'beaufort county', ..., '48TH/D ST', 'E FOOTHILL DR & N STERLING AVE', '9/MTVERNON', '5245 N MTN VIEW AVE', 'EB 210 / SWY']
Length: 254029
Categories (254029, object): ['', '+', '+621X KENNEDY', '-10 W & Read Blvd', ..., 'west side', 'yancey county', 'zmexico', 'zuk']

In [21]:
df['search_basis_cat'] = df['search_basis'].astype('category')
df['county_name_cat'] = df['county_name'].astype('category')
df['subject_race_cat'] = df['subject_race'].astype('category')
df['department_name_cat'] = df['department_name'].astype('category')
df['outcome_cat'] = df['outcome'].astype('category')
df['contraband_found_cat'] = df['contraband_found'].astype('category')
df['contraband_drugs_cat'] = df['contraband_drugs'].astype('category')
df['contraband_weapons_cat'] = df['contraband_weapons'].astype('category')
df['search_basis_cat'] = df['search_basis'].astype('category')
df['reason_for_frisk_cat'] = df['reason_for_frisk'].astype('category')
df['reason_for_search_cat'] = df['reason_for_search'].astype('category')

In [22]:
df['reason_for_stop_cat'] = df['reason_for_stop'].astype('category')
df['raw_action_description_cat'] = df['raw_action_description'].astype('category')
df['subject_sex_cat'] = df['subject_sex'].astype('category')
df['raw_ethnicity_cat'] = df['raw_Ethnicity'].astype('category')

In [24]:
unique_counts = {}

for column in df.columns:
    unique_count = df[column].nunique()
    unique_counts[column] = unique_count
    print(f"Column '{column}' has {unique_count} unique values.")

Column 'raw_row_number' has 3314348 unique values.
Column 'date' has 7483 unique values.
Column 'time' has 137941 unique values.
Column 'location' has 411815 unique values.
Column 'county_name' has 24 unique values.
Column 'subject_age' has 101 unique values.
Column 'subject_race' has 6 unique values.
Column 'subject_sex' has 2 unique values.
Column 'officer_id_hash' has 14397 unique values.
Column 'department_name' has 6 unique values.
Column 'type' has 2 unique values.
Column 'arrest_made' has 2 unique values.
Column 'citation_issued' has 2 unique values.
Column 'warning_issued' has 2 unique values.
Column 'outcome' has 3 unique values.
Column 'contraband_found' has 2 unique values.
Column 'contraband_drugs' has 2 unique values.
Column 'contraband_weapons' has 2 unique values.
Column 'frisk_performed' has 2 unique values.
Column 'search_conducted' has 2 unique values.
Column 'search_person' has 2 unique values.
Column 'search_vehicle' has 2 unique values.
Column 'search_basis' has 4 unique values.
Column 'reason_for_frisk' has 36 unique values.
Column 'reason_for_search' has 63 unique values.
Column 'reason_for_stop' has 180 unique values.
Column 'raw_Ethnicity' has 2 unique values.
Column 'raw_Race' has 5 unique values.
Column 'raw_action_description' has 5 unique values.
Column 'file' has 17 unique values.
Column 'lat' has 226584 unique values.
Column 'lng' has 220133 unique values.
Column 'disposition' has 5446 unique values.
Column 'violation' has 61975 unique values.
Column 'vehicle_color' has 1589 unique values.
Column 'vehicle_make' has 6099 unique values.
Column 'vehicle_type' has 159 unique values.
Column 'vehicle_registration_state' has 51 unique values.
Column 'raw_race' has 42 unique values.
Column 'district' has 20 unique values.
Column 'zone' has 36 unique values.
Column 'officer_assignment' has 84 unique values.
Column 'vehicle_model' has 23088 unique values.
Column 'vehicle_year' has 197 unique values.
Column 'raw_actions_taken' has 10921 unique values.
Column 'raw_subject_race' has 6 unique values.
Column 'division' has 535 unique values.
Column 'speed' has 127 unique values.
Column 'posted_speed' has 97 unique values.
Column 'geocode_source' has 2 unique values.
Column 'raw_ethnicity' has 107 unique values.
Column 'beat' has 188 unique values.
Column 'sector' has 111 unique values.
Column 'unit' has 9 unique values.
Column 'notes' has 24027 unique values.
Column 'raw_contraband' has 21 unique values.
Column 'raw_contraband_found' has 5 unique values.
Column 'raw_results' has 108 unique values.
Column 'raw_defendant_race' has 6 unique values.
Column 'raw_defendant_ethnicity' has 10 unique values.
Column 'raw_statute_name' has 11 unique values.
Column 'raw_statute_section' has 148 unique values.
Column 'neighborhood' has 63 unique values.
Column 'raw_action_taken_cid' has 3518 unique values.
Column 'raw_field_subject_cid' has 59 unique values.
Column 'raw_CallType' has 2 unique values.
Column 'datetime' has 7483 unique values.
Column 'file_source' has 14 unique values.
Column 'location_categorical' has 254029 unique values.
Column 'search_basis_cat' has 4 unique values.
Column 'county_name_cat' has 24 unique values.
Column 'subject_race_cat' has 6 unique values.
Column 'department_name_cat' has 6 unique values.
Column 'outcome_cat' has 3 unique values.
Column 'contraband_found_cat' has 2 unique values.
Column 'contraband_drugs_cat' has 2 unique values.
Column 'contraband_weapons_cat' has 2 unique values.
Column 'reason_for_frisk_cat' has 36 unique values.
Column 'reason_for_search_cat' has 63 unique values.
Column 'reason_for_stop_cat' has 180 unique values.
Column 'raw_action_description_cat' has 5 unique values.
Column 'subject_sex_cat' has 2 unique values.
Column 'raw_ethnicity_cat' has 2 unique values.

In [25]:
df_out = df[['datetime', 'file_source', 'county_name_cat', 'subject_age', 'subject_sex_cat', 'subject_race_cat', 'raw_ethnicity_cat', 'department_name_cat', 'outcome_cat', 'raw_action_description_cat', 'contraband_found_cat', 'contraband_drugs_cat', 'contraband_weapons_cat', 'reason_for_frisk_cat', 'reason_for_search_cat', 'reason_for_stop_cat']]

In [26]:
df_out.to_feather('data_products/national_comparison_reduced_data.feather')

In [27]:
unique_counts = {}

for column in df_out.columns:
    unique_count = df_out[column].nunique()
    unique_counts[column] = unique_count
    print(f"Column '{column}' has {unique_count} unique values.")

Column 'datetime' has 7483 unique values.
Column 'file_source' has 14 unique values.
Column 'county_name_cat' has 24 unique values.
Column 'subject_age' has 101 unique values.
Column 'subject_sex_cat' has 2 unique values.
Column 'subject_race_cat' has 6 unique values.
Column 'raw_ethnicity_cat' has 2 unique values.
Column 'department_name_cat' has 6 unique values.
Column 'outcome_cat' has 3 unique values.
Column 'raw_action_description_cat' has 5 unique values.
Column 'contraband_found_cat' has 2 unique values.
Column 'contraband_drugs_cat' has 2 unique values.
Column 'contraband_weapons_cat' has 2 unique values.
Column 'reason_for_frisk_cat' has 36 unique values.
Column 'reason_for_search_cat' has 63 unique values.
Column 'reason_for_stop_cat' has 180 unique values.